package com.kk.mybatis.entity;

public class CouponKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.coupon_seq
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    private String couponSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.coupon_seq
     *
     * @return the value of t_coupon.coupon_seq
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public String getCouponSeq() {
        return couponSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.coupon_seq
     *
     * @param couponSeq the value for t_coupon.coupon_seq
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public void setCouponSeq(String couponSeq) {
        this.couponSeq = couponSeq == null ? null : couponSeq.trim();
    }
}