package com.kk.mybatis.entity;

import java.util.Date;

public class Coupon extends CouponKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.user_phone
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.template_seq
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    private String templateSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.coupon_status
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    private String couponStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.create_time
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.update_time
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.user_phone
     *
     * @return the value of t_coupon.user_phone
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.user_phone
     *
     * @param userPhone the value for t_coupon.user_phone
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.template_seq
     *
     * @return the value of t_coupon.template_seq
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public String getTemplateSeq() {
        return templateSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.template_seq
     *
     * @param templateSeq the value for t_coupon.template_seq
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public void setTemplateSeq(String templateSeq) {
        this.templateSeq = templateSeq == null ? null : templateSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.coupon_status
     *
     * @return the value of t_coupon.coupon_status
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public String getCouponStatus() {
        return couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.coupon_status
     *
     * @param couponStatus the value for t_coupon.coupon_status
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public void setCouponStatus(String couponStatus) {
        this.couponStatus = couponStatus == null ? null : couponStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.create_time
     *
     * @return the value of t_coupon.create_time
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.create_time
     *
     * @param createTime the value for t_coupon.create_time
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.update_time
     *
     * @return the value of t_coupon.update_time
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.update_time
     *
     * @param updateTime the value for t_coupon.update_time
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}