package com.kk.mybatis.entity;

public class CouponTemplateKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_template.template_seq
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    private String templateSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_template.template_seq
     *
     * @return the value of t_coupon_template.template_seq
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public String getTemplateSeq() {
        return templateSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_template.template_seq
     *
     * @param templateSeq the value for t_coupon_template.template_seq
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    public void setTemplateSeq(String templateSeq) {
        this.templateSeq = templateSeq == null ? null : templateSeq.trim();
    }
}