

spring:
  data: #redis
    redis:
      database: 0
      host: 127.0.0.1 #120.48.53.93
      port: 6379
      password: #aopy80
      lettuce:
        pool:
          max-active: 8  #????????
          max-wait: -1ms #???????????
          max-idle: 8 # ???????????
          min-idle: 0 # ???????????
    #  timeout: 5000ms # ??????????
server: #???
  port: 8801
