spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://####?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ###
    password: ###
mybatis:
  mapper-locations: classpath:mapper/*.xml
