package com.kk.mybatis.mapper;

import com.kk.mybatis.entity.Coupon;
import com.kk.mybatis.entity.CouponKey;

public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    int deleteByPrimaryKey(CouponKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    int insert(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    int insertSelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    Coupon selectByPrimaryKey(CouponKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    int updateByPrimaryKeySelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    int updateByPrimaryKey(Coupon record);
}