package com.kk.mybatis.mapper;

import com.kk.mybatis.entity.CouponTemplate;
import com.kk.mybatis.entity.CouponTemplateKey;

public interface CouponTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_template
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    int deleteByPrimaryKey(CouponTemplateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_template
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    int insert(CouponTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_template
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    int insertSelective(CouponTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_template
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    CouponTemplate selectByPrimaryKey(CouponTemplateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_template
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    int updateByPrimaryKeySelective(CouponTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_template
     *
     * @mbg.generated Sat Sep 16 15:02:14 CST 2023
     */
    int updateByPrimaryKey(CouponTemplate record);
}